#Configuration file for Bar Code Nodelet

#Config Symbol Type
#Cf. http://zbar.sourceforge.net/api/zbar_8h.html#f7818ad6458f9f40362eecda97acdcb0

#ZBAR_NONE        =      0  no symbol decoded (use it for any symbol)
#ZBAR_PARTIAL     =      1  intermediate status
#ZBAR_EAN8        =      8  EAN-8.
#ZBAR_UPCE        =      9  UPC-E.
#ZBAR_ISBN10      =     10  ISBN-10 (from EAN-13).
#ZBAR_UPCA        =     12  UPC-A.
#ZBAR_EAN13       =     13  EAN-13.
#ZBAR_ISBN13      =     14  ISBN-13 (from EAN-13).
#ZBAR_I25         =     25  Interleaved 2 of 5.
#ZBAR_CODE39      =     39  Code 39.
#ZBAR_PDF417      =     57  PDF417.
#ZBAR_QRCODE      =     64  QR Code.
#ZBAR_CODE128     =    128  Code 128.

symbol_type: 64
